apiVersion: apps/v1
kind: Deployment
metadata:
  name: adsoftsito-phd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adsoftsito-phd
  template:
    metadata:
      labels:
        app: adsoftsito-phd
    spec:
      containers:
      - image: okteto.dev/adsoftsito-phd:latest
        name: adsoftsito-phd
        envFrom:
        - configMapRef:
          name: adsoftsito-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: adsoftsito-phd
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "adsoftsito-phd"
    port: 8080
  selector:
    app: adsoftsito-phd
